#pragma once

enum Error {
    INVALID_ARGC,
    EMPTY_ARGS,
    NUMERIC_PORT,
    PORT_RANGE,
    PASS_TOO_LONG,
    CREATING_SOCKET,
    CONFIGURING_SOCKET,
    BINDING_SOCKET,
    FCNTL_ERROR,
    LISTENING_SOCKET,
    ACCEPTING_CONNECTION,
    READING_RECV
};