#pragma once

enum Res {
    NOT_ENOUGH_PARAMS,
    ENOUGH_PARAMS,
    USER_ALREADY_REGISTERED,
    USER_ALREADY_AUTHENTICATED,
    INCORRERCT_PASSWORD,
    NO_NICKNAME_GIVEN,
    NICKNAME_IN_USE,
    ERRONEOUS_NICKNAME,
    RPL_WELCOME,
    RPL_YOURHOST,
    RPL_CREATED,
    NICKNAME_REGISTERED,
    SEND_PRIVATE_MESSAGE,
    UNKNWON_COMMAND,
    ERR_NORECIPIENT,
    NO_TEXT_TO_SEND,
    ERR_NOSUCHNICK
};
